server:
   port: 8082

elasticsearch:
   connection.url: elasticsearch:9200

spring:
  jackson:
     serialization:
         write_dates_as_timestamps: false
  application:
    name: patient-service
  cloud:
      loadbalancer:
         ribbon:
           enabled: false
      consul:
         host: http://consul
         port: 8500
         config:
           enabled: false
         discovery:
           healthCheckInterval: 15s
           instance-id: patient-service
         load-balancer:
           ribbon:
             enabled: false
      vault:
        url: http://vault:8200
        token: 00000000-0000-0000-0000-000000000000
        scheme: http
        host: vault
        port: 8200
        kv:
         enabled: true
         backend: secret
         application-name: hospitalmanagementsystem
  datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}
      hikari:
         maximum-pool-size: 20
         max-lifetime: 1800000
         idle-timeout: 30000
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    elasticsearch:
     cluster-name: elasticsearch
     cluster-nodes: elasticsearch:9200

management:
   health:
      elasticsearch:
         enabled: false
   endpoints:
       web:
         exposure:
             include: '*'

api:
   username: ${api_username}
   password: ${api_password}
   secretKey: ${secret_key}
   userServiceAccessToken: ${userServiceAccessToken}

logging:
   level:
     com:
       zaxxer:
         hikari: DEBUG