server:
   port: 8083

spring:
  application:
    name: vital-sign-service
  cloud:
      loadbalancer:
         ribbon:
           enabled: false
      consul:
         host: http://consul
         port: 8500
         config:
           enabled: false
         discovery:
           healthCheckInterval: 15s
           instance-id: vital-sign-service
         load-balancer:
           ribbon:
             enabled: false
      vault:
        url: http://vault:8200
        token: 00000000-0000-0000-0000-000000000000
        scheme: http
        host: vault
        port: 8200
        kv:
         enabled: true
         backend: secret
         application-name: hospitalmanagementsystem

  datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
   endpoints:
       web:
         exposure:
             include: '*'

api:
   username: ${api_username}
   password: ${api_password}
   secretKey: ${secret_key}
   userServiceAccessToken: ${userServiceAccessToken}
   patientServiceAccessToken: ${patientServiceAccessToken}